package com.xd.zijing.entity;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.adminID
     *
     * @mbggenerated
     */
    private Integer adminid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.adminUsername
     *
     * @mbggenerated
     */
    private String adminusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admininfo.adminPassword
     *
     * @mbggenerated
     */
    private String adminpassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.adminID
     *
     * @return the value of admininfo.adminID
     *
     * @mbggenerated
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.adminID
     *
     * @param adminid the value for admininfo.adminID
     *
     * @mbggenerated
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.adminUsername
     *
     * @return the value of admininfo.adminUsername
     *
     * @mbggenerated
     */
    public String getAdminusername() {
        return adminusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.adminUsername
     *
     * @param adminusername the value for admininfo.adminUsername
     *
     * @mbggenerated
     */
    public void setAdminusername(String adminusername) {
        this.adminusername = adminusername == null ? null : adminusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admininfo.adminPassword
     *
     * @return the value of admininfo.adminPassword
     *
     * @mbggenerated
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admininfo.adminPassword
     *
     * @param adminpassword the value for admininfo.adminPassword
     *
     * @mbggenerated
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword == null ? null : adminpassword.trim();
    }

    @Override
    public String toString() {
        return "Admin{" +
                "adminid=" + adminid +
                ", adminusername='" + adminusername + '\'' +
                ", adminpassword='" + adminpassword + '\'' +
                '}';
    }
}