package com.xd.zijing.entity;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.userID
     *
     * @mbggenerated
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.age
     *
     * @mbggenerated
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.balance
     *
     * @mbggenerated
     */
    private Float balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.phone
     *
     * @mbggenerated
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.department
     *
     * @mbggenerated
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.leader
     *
     * @mbggenerated
     */
    private String leader;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.userID
     *
     * @return the value of userinfo.userID
     *
     * @mbggenerated
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.userID
     *
     * @param userid the value for userinfo.userID
     *
     * @mbggenerated
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.username
     *
     * @return the value of userinfo.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.username
     *
     * @param username the value for userinfo.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.age
     *
     * @return the value of userinfo.age
     *
     * @mbggenerated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.age
     *
     * @param age the value for userinfo.age
     *
     * @mbggenerated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.account
     *
     * @return the value of userinfo.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.account
     *
     * @param account the value for userinfo.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.password
     *
     * @return the value of userinfo.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.password
     *
     * @param password the value for userinfo.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.gender
     *
     * @return the value of userinfo.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.gender
     *
     * @param gender the value for userinfo.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.balance
     *
     * @return the value of userinfo.balance
     *
     * @mbggenerated
     */
    public Float getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.balance
     *
     * @param balance the value for userinfo.balance
     *
     * @mbggenerated
     */
    public void setBalance(Float balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.email
     *
     * @return the value of userinfo.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.email
     *
     * @param email the value for userinfo.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.phone
     *
     * @return the value of userinfo.phone
     *
     * @mbggenerated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.phone
     *
     * @param phone the value for userinfo.phone
     *
     * @mbggenerated
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.title
     *
     * @return the value of userinfo.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.title
     *
     * @param title the value for userinfo.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.department
     *
     * @return the value of userinfo.department
     *
     * @mbggenerated
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.department
     *
     * @param department the value for userinfo.department
     *
     * @mbggenerated
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.leader
     *
     * @return the value of userinfo.leader
     *
     * @mbggenerated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.leader
     *
     * @param leader the value for userinfo.leader
     *
     * @mbggenerated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    public Employee() {}

    public Employee(Long userid, String username, Integer age, String account, String password, String gender, Float balance, String email, Integer phone, String title, String department, String leader) {
        this.userid = userid;
        this.username = username;
        this.age = age;
        this.account = account;
        this.password = password;
        this.gender = gender;
        this.balance = balance;
        this.email = email;
        this.phone = phone;
        this.title = title;
        this.department = department;
        this.leader = leader;
    }

    public Employee(String username, Integer age, String account, String password, String gender, Float balance, String email, Integer phone, String title, String department, String leader) {
        this.username = username;
        this.age = age;
        this.account = account;
        this.password = password;
        this.gender = gender;
        this.balance = balance;
        this.email = email;
        this.phone = phone;
        this.title = title;
        this.department = department;
        this.leader = leader;
    }



    @Override
    public String toString() {
        return "Employee{" +
                "username='" + username + '\'' +
                ", age=" + age +
                ", gender='" + gender + '\'' +
                ", title='" + title + '\'' +
                ", department='" + department + '\'' +
                ", leader='" + leader + '\'' +
                '}';
    }
}