package com.six.FilmAndTelevisionBusiness.entity;

import java.util.Date;

public class Screening {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.screeningNumber
     *
     * @mbggenerated
     */
    private Long screeningnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.filmName
     *
     * @mbggenerated
     */
    private String filmname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.cinemaName
     *
     * @mbggenerated
     */
    private String cinemaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.hallName
     *
     * @mbggenerated
     */
    private String hallname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.saleTime
     *
     * @mbggenerated
     */
    private Date saletime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.releaseTime
     *
     * @mbggenerated
     */
    private Date releasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.ticketNumber
     *
     * @mbggenerated
     */
    private Integer ticketnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.unsoldTicketNumber
     *
     * @mbggenerated
     */
    private Integer unsoldticketnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.soldTicketNumber
     *
     * @mbggenerated
     */
    private Integer soldticketnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column screeninginfo.price
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.screeningNumber
     *
     * @return the value of screeninginfo.screeningNumber
     *
     * @mbggenerated
     */
    public Long getScreeningnumber() {
        return screeningnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.screeningNumber
     *
     * @param screeningnumber the value for screeninginfo.screeningNumber
     *
     * @mbggenerated
     */
    public void setScreeningnumber(Long screeningnumber) {
        this.screeningnumber = screeningnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.filmName
     *
     * @return the value of screeninginfo.filmName
     *
     * @mbggenerated
     */
    public String getFilmname() {
        return filmname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.filmName
     *
     * @param filmname the value for screeninginfo.filmName
     *
     * @mbggenerated
     */
    public void setFilmname(String filmname) {
        this.filmname = filmname == null ? null : filmname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.cinemaName
     *
     * @return the value of screeninginfo.cinemaName
     *
     * @mbggenerated
     */
    public String getCinemaname() {
        return cinemaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.cinemaName
     *
     * @param cinemaname the value for screeninginfo.cinemaName
     *
     * @mbggenerated
     */
    public void setCinemaname(String cinemaname) {
        this.cinemaname = cinemaname == null ? null : cinemaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.hallName
     *
     * @return the value of screeninginfo.hallName
     *
     * @mbggenerated
     */
    public String getHallname() {
        return hallname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.hallName
     *
     * @param hallname the value for screeninginfo.hallName
     *
     * @mbggenerated
     */
    public void setHallname(String hallname) {
        this.hallname = hallname == null ? null : hallname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.saleTime
     *
     * @return the value of screeninginfo.saleTime
     *
     * @mbggenerated
     */
    public Date getSaletime() {
        return saletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.saleTime
     *
     * @param saletime the value for screeninginfo.saleTime
     *
     * @mbggenerated
     */
    public void setSaletime(Date saletime) {
        this.saletime = saletime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.releaseTime
     *
     * @return the value of screeninginfo.releaseTime
     *
     * @mbggenerated
     */
    public Date getReleasetime() {
        return releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.releaseTime
     *
     * @param releasetime the value for screeninginfo.releaseTime
     *
     * @mbggenerated
     */
    public void setReleasetime(Date releasetime) {
        this.releasetime = releasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.ticketNumber
     *
     * @return the value of screeninginfo.ticketNumber
     *
     * @mbggenerated
     */
    public Integer getTicketnumber() {
        return ticketnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.ticketNumber
     *
     * @param ticketnumber the value for screeninginfo.ticketNumber
     *
     * @mbggenerated
     */
    public void setTicketnumber(Integer ticketnumber) {
        this.ticketnumber = ticketnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.unsoldTicketNumber
     *
     * @return the value of screeninginfo.unsoldTicketNumber
     *
     * @mbggenerated
     */
    public Integer getUnsoldticketnumber() {
        return unsoldticketnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.unsoldTicketNumber
     *
     * @param unsoldticketnumber the value for screeninginfo.unsoldTicketNumber
     *
     * @mbggenerated
     */
    public void setUnsoldticketnumber(Integer unsoldticketnumber) {
        this.unsoldticketnumber = unsoldticketnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.soldTicketNumber
     *
     * @return the value of screeninginfo.soldTicketNumber
     *
     * @mbggenerated
     */
    public Integer getSoldticketnumber() {
        return soldticketnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.soldTicketNumber
     *
     * @param soldticketnumber the value for screeninginfo.soldTicketNumber
     *
     * @mbggenerated
     */
    public void setSoldticketnumber(Integer soldticketnumber) {
        this.soldticketnumber = soldticketnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column screeninginfo.price
     *
     * @return the value of screeninginfo.price
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column screeninginfo.price
     *
     * @param price the value for screeninginfo.price
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }
}