package com.six.FilmAndTelevisionBusiness.entity;

public class Struct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structinfo.departmentID
     *
     * @mbggenerated
     */
    private Integer departmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structinfo.cinemaName
     *
     * @mbggenerated
     */
    private String cinemaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structinfo.departmentName
     *
     * @mbggenerated
     */
    private String departmentname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structinfo.leader
     *
     * @mbggenerated
     */
    private String leader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structinfo.higherDepartmentID
     *
     * @mbggenerated
     */
    private Integer higherdepartmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column structinfo.isTop
     *
     * @mbggenerated
     */
    private Integer istop;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structinfo.departmentID
     *
     * @return the value of structinfo.departmentID
     *
     * @mbggenerated
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structinfo.departmentID
     *
     * @param departmentid the value for structinfo.departmentID
     *
     * @mbggenerated
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structinfo.cinemaName
     *
     * @return the value of structinfo.cinemaName
     *
     * @mbggenerated
     */
    public String getCinemaname() {
        return cinemaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structinfo.cinemaName
     *
     * @param cinemaname the value for structinfo.cinemaName
     *
     * @mbggenerated
     */
    public void setCinemaname(String cinemaname) {
        this.cinemaname = cinemaname == null ? null : cinemaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structinfo.departmentName
     *
     * @return the value of structinfo.departmentName
     *
     * @mbggenerated
     */
    public String getDepartmentname() {
        return departmentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structinfo.departmentName
     *
     * @param departmentname the value for structinfo.departmentName
     *
     * @mbggenerated
     */
    public void setDepartmentname(String departmentname) {
        this.departmentname = departmentname == null ? null : departmentname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structinfo.leader
     *
     * @return the value of structinfo.leader
     *
     * @mbggenerated
     */
    public String getLeader() {
        return leader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structinfo.leader
     *
     * @param leader the value for structinfo.leader
     *
     * @mbggenerated
     */
    public void setLeader(String leader) {
        this.leader = leader == null ? null : leader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structinfo.higherDepartmentID
     *
     * @return the value of structinfo.higherDepartmentID
     *
     * @mbggenerated
     */
    public Integer getHigherdepartmentid() {
        return higherdepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structinfo.higherDepartmentID
     *
     * @param higherdepartmentid the value for structinfo.higherDepartmentID
     *
     * @mbggenerated
     */
    public void setHigherdepartmentid(Integer higherdepartmentid) {
        this.higherdepartmentid = higherdepartmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column structinfo.isTop
     *
     * @return the value of structinfo.isTop
     *
     * @mbggenerated
     */
    public Integer getIstop() {
        return istop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column structinfo.isTop
     *
     * @param istop the value for structinfo.isTop
     *
     * @mbggenerated
     */
    public void setIstop(Integer istop) {
        this.istop = istop;
    }

    @Override
    public String toString() {
        return "Struct{" +
                "departmentid=" + departmentid +
                ", cinemaname='" + cinemaname + '\'' +
                ", departmentname='" + departmentname + '\'' +
                ", leader='" + leader + '\'' +
                ", higherdepartmentid=" + higherdepartmentid +
                ", istop=" + istop +
                '}';
    }
}