package com.six.FilmAndTelevisionBusiness.entity;

import java.util.Date;

public class Vip {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipID
     *
     * @mbggenerated
     */
    private Integer vipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipName
     *
     * @mbggenerated
     */
    private String vipname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipUsername
     *
     * @mbggenerated
     */
    private String vipusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipPassword
     *
     * @mbggenerated
     */
    private String vippassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipTelephone
     *
     * @mbggenerated
     */
    private String viptelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipRank
     *
     * @mbggenerated
     */
    private String viprank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipTotal
     *
     * @mbggenerated
     */
    private Integer viptotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipBalance
     *
     * @mbggenerated
     */
    private Integer vipbalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipGender
     *
     * @mbggenerated
     */
    private String vipgender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipBirthday
     *
     * @mbggenerated
     */
    private Date vipbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipLastLogin
     *
     * @mbggenerated
     */
    private Date viplastlogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vipdata.VipRegisterDate
     *
     * @mbggenerated
     */
    private Date vipregisterdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipID
     *
     * @return the value of vipdata.VipID
     *
     * @mbggenerated
     */
    public Integer getVipid() {
        return vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipID
     *
     * @param vipid the value for vipdata.VipID
     *
     * @mbggenerated
     */
    public void setVipid(Integer vipid) {
        this.vipid = vipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipName
     *
     * @return the value of vipdata.VipName
     *
     * @mbggenerated
     */
    public String getVipname() {
        return vipname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipName
     *
     * @param vipname the value for vipdata.VipName
     *
     * @mbggenerated
     */
    public void setVipname(String vipname) {
        this.vipname = vipname == null ? null : vipname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipUsername
     *
     * @return the value of vipdata.VipUsername
     *
     * @mbggenerated
     */
    public String getVipusername() {
        return vipusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipUsername
     *
     * @param vipusername the value for vipdata.VipUsername
     *
     * @mbggenerated
     */
    public void setVipusername(String vipusername) {
        this.vipusername = vipusername == null ? null : vipusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipPassword
     *
     * @return the value of vipdata.VipPassword
     *
     * @mbggenerated
     */
    public String getVippassword() {
        return vippassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipPassword
     *
     * @param vippassword the value for vipdata.VipPassword
     *
     * @mbggenerated
     */
    public void setVippassword(String vippassword) {
        this.vippassword = vippassword == null ? null : vippassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipTelephone
     *
     * @return the value of vipdata.VipTelephone
     *
     * @mbggenerated
     */
    public String getViptelephone() {
        return viptelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipTelephone
     *
     * @param viptelephone the value for vipdata.VipTelephone
     *
     * @mbggenerated
     */
    public void setViptelephone(String viptelephone) {
        this.viptelephone = viptelephone == null ? null : viptelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipRank
     *
     * @return the value of vipdata.VipRank
     *
     * @mbggenerated
     */
    public String getViprank() {
        return viprank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipRank
     *
     * @param viprank the value for vipdata.VipRank
     *
     * @mbggenerated
     */
    public void setViprank(String viprank) {
        this.viprank = viprank == null ? null : viprank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipTotal
     *
     * @return the value of vipdata.VipTotal
     *
     * @mbggenerated
     */
    public Integer getViptotal() {
        return viptotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipTotal
     *
     * @param viptotal the value for vipdata.VipTotal
     *
     * @mbggenerated
     */
    public void setViptotal(Integer viptotal) {
        this.viptotal = viptotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipBalance
     *
     * @return the value of vipdata.VipBalance
     *
     * @mbggenerated
     */
    public Integer getVipbalance() {
        return vipbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipBalance
     *
     * @param vipbalance the value for vipdata.VipBalance
     *
     * @mbggenerated
     */
    public void setVipbalance(Integer vipbalance) {
        this.vipbalance = vipbalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipGender
     *
     * @return the value of vipdata.VipGender
     *
     * @mbggenerated
     */
    public String getVipgender() {
        return vipgender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipGender
     *
     * @param vipgender the value for vipdata.VipGender
     *
     * @mbggenerated
     */
    public void setVipgender(String vipgender) {
        this.vipgender = vipgender == null ? null : vipgender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipBirthday
     *
     * @return the value of vipdata.VipBirthday
     *
     * @mbggenerated
     */
    public Date getVipbirthday() {
        return vipbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipBirthday
     *
     * @param vipbirthday the value for vipdata.VipBirthday
     *
     * @mbggenerated
     */
    public void setVipbirthday(Date vipbirthday) {
        this.vipbirthday = vipbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipLastLogin
     *
     * @return the value of vipdata.VipLastLogin
     *
     * @mbggenerated
     */
    public Date getViplastlogin() {
        return viplastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipLastLogin
     *
     * @param viplastlogin the value for vipdata.VipLastLogin
     *
     * @mbggenerated
     */
    public void setViplastlogin(Date viplastlogin) {
        this.viplastlogin = viplastlogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vipdata.VipRegisterDate
     *
     * @return the value of vipdata.VipRegisterDate
     *
     * @mbggenerated
     */
    public Date getVipregisterdate() {
        return vipregisterdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vipdata.VipRegisterDate
     *
     * @param vipregisterdate the value for vipdata.VipRegisterDate
     *
     * @mbggenerated
     */
    public void setVipregisterdate(Date vipregisterdate) {
        this.vipregisterdate = vipregisterdate;
    }

    @Override
    public String toString() {
        return "Vip{" +
                "vipid=" + vipid +
                ", vipname='" + vipname + '\'' +
                ", vipusername='" + vipusername + '\'' +
                ", vippassword='" + vippassword + '\'' +
                ", viptelephone='" + viptelephone + '\'' +
                ", viprank='" + viprank + '\'' +
                ", viptotal=" + viptotal +
                ", vipbalance=" + vipbalance +
                ", vipgender='" + vipgender + '\'' +
                ", vipbirthday=" + vipbirthday +
                ", viplastlogin=" + viplastlogin +
                ", vipregisterdate=" + vipregisterdate +
                '}';
    }
}