package com.xd.zijing.mapper;

import com.xd.zijing.entity.Admin;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer adminid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbggenerated
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbggenerated
     */
    int insertSelective(Admin record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbggenerated
     */
    Admin selectByPrimaryKey(Integer adminid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admininfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Admin record);


    int countAll();

    List<Admin> selectAll(@Param("start")int start,@Param("pageSize")int pageSize);
}