package com.six.FilmAndTelevisionBusiness.mapper;

import com.six.FilmAndTelevisionBusiness.entity.Screening;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScreeningMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screeninginfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long screeningnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screeninginfo
     *
     * @mbggenerated
     */
    int insert(Screening record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screeninginfo
     *
     * @mbggenerated
     */
    int insertSelective(Screening record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screeninginfo
     *
     * @mbggenerated
     */
    Screening selectByPrimaryKey(Long screeningnumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screeninginfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Screening record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table screeninginfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Screening record);


    int countAll();
    List<Screening> selectAll(@Param("start") int start, @Param("pageSize") int pageSize);
}