package com.xd.zijing.mapper;

import com.xd.zijing.entity.Struct;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface StructMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structinfo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer departmentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structinfo
     *
     * @mbggenerated
     */
    int insert(Struct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structinfo
     *
     * @mbggenerated
     */
    int insertSelective(Struct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structinfo
     *
     * @mbggenerated
     */
    Struct selectByPrimaryKey(Integer departmentid);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Struct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table structinfo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Struct record);
    int countAll();

    List<Struct> selectAll(@Param("start") int start, @Param("pageSize") int pageSize);
}