package com.xd.zijing.mapper;

import com.xd.zijing.entity.Vip;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface VipMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipdata
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer vipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipdata
     *
     * @mbggenerated
     */
    int insert(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipdata
     *
     * @mbggenerated
     */
    int insertSelective(Vip record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipdata
     *
     * @mbggenerated
     */
    Vip selectByPrimaryKey(Integer vipid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Vip record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vipdata
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Vip record);

    int countAll();

    List<Vip> selectAll(@Param("start") int start, @Param("pageSize") int pageSize);
}
